name: Run API and UI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run API Tests
        run: mvn -Dtest=LoginRelatedTest,DelayAPITest,NegativeAPITest,UserRelatedAPITest test

      - name: Archive API test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-surefire-reports
          path: target/surefire-reports

  ui-tests:
    name: Run UI Tests
    runs-on: ubuntu-latest
    needs: api-tests  # optional: run UI after API tests

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run UI Tests
        run: mvn -Dtest=LoginUITest test

      - name: Archive UI test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-surefire-reports
          path: target/surefire-reports
